### ISSUE TITLE
logspout:v0.2.0 not work (logstash:1.5.6-1, elasticsearch-2)

### ISSUE THREAD

**Issue by Negashev** [rancher/community-catalog#109]
I run:
1) elasticsearch-2
[elasticsearch-2.zip](https://github.com/rancher/community-catalog/files/223202/elasticsearch-2.zip)
2) logstash
[logstash.zip](https://github.com/rancher/community-catalog/files/223204/logstash.zip)
3) logspout
[logspout.zip](https://github.com/rancher/community-catalog/files/223206/logspout.zip)

In logs Logspout connect to Logstash, but not send logs from servers.

In old version elasticsearch (and logstash) all work, i can use kibana, but now ES-2 not get data
docker-compose.yml 
```yaml
logspout:
  environment:
    LOGSPOUT: ignore
    ROUTE_URIS: logstash://logstash:5000
  external_links:
  - logstash/logstash-collector:logstash
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.hostname_override: container_name
  tty: true
  image: rancher/logspout-logstash:v0.2.0
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  stdin_open: true
```

kopf:
![screenshot 2](https://cloud.githubusercontent.com/assets/4653589/14596283/d32d7f2a-055e-11e6-85e4-1db14f31dabe.png)
