### ISSUE TITLE
[cloudflare] unmarshal number error of type string

### ISSUE THREAD

**Issue by sdurrheimer** [rancher/community-catalog#118]
Hi, 

I'm encountering an error while testing the CloudFlare DNS Service.
```
23/4/2016 23:24:30time="2016-04-23T21:24:30Z" level=fatal msg="Failed to set zone for root domain domain.tld: CloudFlare API call has failed: json: cannot unmarshal number into Go value of type string"
```

Corresponding config files:

docker-compose.yml
```yml
cloudflare:
  environment:
    CLOUDFLARE_EMAIL: s.durrheimer@gmail.com
    CLOUDFLARE_KEY: 9534129bbb1f22bc71973d4cd90a429xxxxxx
    ROOT_DOMAIN: domain.tld
    TTL: '300'
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: external-dns
  command:
  - -provider=cloudflare
  image: rancher/external-dns:v0.2.1
```

rancher-compose.yml
```yml
cloudflare:
  scale: 1
  health_check:
    port: 1000
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
```

Precision: I have deliberatly obfuscated the end of the API_KEY.
