### ISSUE TITLE
RabbitMQ unreachable from outside? (rancher 1.2)

### ISSUE THREAD

**Issue by lilnate22** [rancher/community-catalog#322]
Deployed Rancher rabbitMQ via the catalog.

I see that it is also deploying the management plugin (port 15672) but that doesn't seem to be reachable when I go to the node public port.

also clicking on the individual container, i dont see any ports listed:

![image](https://cloud.githubusercontent.com/assets/882236/19730660/eea13332-9b68-11e6-9515-7f9098a1baea.png)

where as running the wordpress one you can clearly see port 80 listed under ports.

it seems rabbitMQ is not exposing the ports to connections to the outside. is this by design?

**Comment by ddmng** [comment]
RabbitMQ service does not expose any port by design. If you want to access to the management UI or reach the AMPQ port just add a Load Balancer from Rancher mapping the internal `15672` and `5672` ports respectively.

**Comment by lilnate22** [comment]
@ddmng  is this true for rabbitMQ connections as well? (i.e 5672)

**Comment by ddmng** [comment]
@lilnate22 Yes, same behavior, although I would prefer using a rancher service link to interact with rabbit from other rancher services.

**Comment by dminnear** [comment]
Just a heads up that there seems to be an issue with the most recent catalog item for rabbit. `0.2.0` is working fine. I can connect to the management server by adding a service rule to my loadbalancer. In `0.2.1` though, any attempt to hit `15672` gives a 503. For anyone else wondering wtf is up with rabbit not being reachable in the latest, try using the `0.2.0` template.

**Comment by ddmng** [comment]
@dminnear already opened an issue for this bug? I try to setup a 0.2.1 to replicate.

@rawmind0 there seem to be an issue with rabbit 0.2.1 that 0.2.0 did not have. Any idea on what has been introduced in 0.2.1?

**Comment by rawmind0** [comment]
@dminnear , i deployed rabbit `v0.2.0` and `v0.2.1`. Both seems working fine accessing ports `15672` and `5672` from rancher lb. Could you provide more info or details about your issues??

@ddmng , some changes between 2 versions options. Deployments are almost the same, just `0.2.1` is using alpine images.

**Comment by dminnear** [comment]
@rawmind0 If it's working for you, it may have been a quirk in my setup. I'll try and replicate it this week and if I can I'll make a new issue with the details. Thanks for looking into this!

**Comment by junkiebev** [comment]
I'm having this same issue when I try to use the rancher-nfs volume driver and only then.

I'm using Rancher v1.6.16

**Comment by junkiebev** [comment]
This seems to work:
```
version: '2'
volumes:
  rabbitconf:
    driver: local
    per_container: true
  rancherbin:
    driver: local
    per_container: true
  ranchermnesia:
    driver: rancher-nfs
    per_container: true
services:
  rabbitmq-datavolume:
    image: rabbitmq:3.6-management-alpine
    entrypoint:
    - /bin/true
    network_mode: none
    volumes:
    - rabbitconf:/etc/rabbitmq
    - rancherbin:/opt/rancher/bin
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  rabbitmq-mnesia:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '101'
      SERVICE_UID: '100'
      SERVICE_VOLUME: /var/lib/rabbitmq
    network_mode: none
    volumes:
    - ranchermnesia:/var/lib/rabbitmq
    labels:
      io.rancher.container.start_once: 'true'
  rabbitmq:
    image: webhostingcoopteam/rabbitmq-conf:0.2.1
    environment:
      CONFD_ARGS: --interval 5
      RABBITMQ_CLUSTER_PARTITION_HANDLING: autoheal
      RABBITMQ_NET_TICKTIME: '60'
    volumes_from:
    - rabbitmq-datavolume
    - rabbitmq-mnesia
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: rabbitmq-base,rabbitmq-datavolume,rabbitmq-mnesia
      io.rancher.container.hostname_override: container_name
  rabbitmq-base:
    image: rabbitmq:3.6-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: defaultcookie
    entrypoint:
    - /opt/rancher/bin/run.sh
    network_mode: container:rabbitmq
    volumes_from:
    - rabbitmq-datavolume
    - rabbitmq-mnesia
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
```
