### ISSUE TITLE
Unable to setup registry stack: 502 Bad Gateway

### ISSUE THREAD

**Issue by danawoodman** [rancher/community-catalog#40]
Hello, 

Trying to get the "registry" stack working but not able to. I'm hitting a 502 Bad Gateway NGINX error when connecting to https://registry.mydomain.com. 

I configured the stack to use `registry.mydomain.com` as the FQDN and used the default ports (`5000`/`443`). 

Here is my `docker-compose.yml`:

``` yaml
db:
  environment:
    MYSQL_DATABASE: portus
    MYSQL_PASSWORD: mypasswordhere
    MYSQL_ROOT_PASSWORD: mypasswordhere
    MYSQL_USER: portus
  labels:
    io.rancher.service.hash: 1e0b6e32ffafa0a0b0b9250e7540d97fe5fdce9d
  tty: true
  image: mysql:5.7.10
  volumes:
  - /var/docker-registry/db:/var/lib/mysql
  stdin_open: true
sslproxy:
  labels:
    io.rancher.service.hash: d12f9cfbe6ef4cf67459c96af4096fd7d4feb0c4
  tty: true
  image: nginx:1.9.9
  links:
  - portus:portus
  volumes:
  - /var/docker-registry/certs:/etc/nginx/certs:ro
  - /var/docker-registry/proxy:/etc/nginx/conf.d:ro
  stdin_open: true
lb:
  ports:
  - 5000:5000/tcp
  - 443:443/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:not_host_label: lb=0
    io.rancher.loadbalancer.target.sslproxy: 443=443
    io.rancher.service.hash: d7d36fab64ca84d9c4967ea01f47bff1ee5343f4
    io.rancher.loadbalancer.target.registry: 5000=5000
  tty: true
  image: rancher/load-balancer-service
  links:
  - registry:registry
  - sslproxy:sslproxy
  stdin_open: true
registry:
  environment:
    REGISTRY_AUTH_TOKEN_ISSUER: registry.mydomain.com
    REGISTRY_AUTH_TOKEN_REALM: https://registry.mydomain.com:443/v2/token
    REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/registry.crt
    REGISTRY_AUTH_TOKEN_SERVICE: registry.mydomain.com:5000
    REGISTRY_HTTP_SECRET: httpsecret
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
    REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    REGISTRY_LOG_LEVEL: warn
    REGISTRY_NOTIFICATIONS_ENDPOINTS: |
      - name: portus
        url: http://portus:3000/v2/webhooks/events
        timeout: 500
        threshold: 5
        backoff: 1
    REGISTRY_STORAGE_DELETE_ENABLED: 'true'
  labels:
    io.rancher.service.hash: 6eccbc547093b7269e5f2abc71829a027ff43a65
  tty: true
  image: registry:2.1
  links:
  - portus:portus
  volumes:
  - /var/docker-registry/certs:/certs:ro
  - /var/docker-registry/data:/var/lib/registry
  stdin_open: true
portus:
  environment:
    PORTUS_CHECK_SSL_USAGE_ENABLED: 'true'
    PORTUS_GRAVATAR_ENABLED: 'true'
    PORTUS_KEY_PATH: /certs/registry.key
    PORTUS_LDAP_AUTHENTICATION_BIND_DN: ou=portus,dc=company,dc=com
    PORTUS_LDAP_AUTHENTICATION_ENABLED: 'false'
    PORTUS_LDAP_AUTHENTICATION_PASSWORD: password
    PORTUS_LDAP_BASE: ou=People,dc=company,dc=com
    PORTUS_LDAP_ENABLED: 'false'
    PORTUS_LDAP_GUESS_EMAIL_ATTR: mail
    PORTUS_LDAP_GUESS_EMAIL_ENABLED: 'true'
    PORTUS_LDAP_HOSTNAME: ldap.company.com
    PORTUS_LDAP_METHOD: starttls
    PORTUS_LDAP_PORT: '389'
    PORTUS_LDAP_UID: cn
    PORTUS_MACHINE_FQDN: registry.mydomain.com
    PORTUS_PASSWORD: mypasswordhere
    PORTUS_PORT: '443'
    PORTUS_PRODUCTION_DATABASE: portus
    PORTUS_PRODUCTION_HOST: db
    PORTUS_PRODUCTION_PASSWORD: mypasswordhere
    PORTUS_PRODUCTION_USERNAME: portus
    PORTUS_SECRET_KEY_BASE: mypasswordhere
    PORTUS_SMTP_ENABLED: 'false'
    REGISTRY_HOSTNAME: registry.mydomain.com
    REGISTRY_NAME: Registry
    REGISTRY_PORT: '5000'
    REGISTRY_SSL_ENABLED: 'true'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.service.hash: efe4408dc0c6702a602249112ddc49d184f133ef
  tty: true
  image: sshipway/portus:2.0.3
  links:
  - db:db
  volumes:
  - /var/docker-registry/certs:/certs
  - /var/docker-registry/proxy:/etc/nginx/conf.d
  stdin_open: true
```

Here is my `rancher-compose.yml`:

``` yaml
db:
  scale: 1
  metadata:
    io.rancher.service.hash: d207d194d16104535c1df27c1c9ac5918b7cfa26
sslproxy:
  scale: 1
  metadata:
    io.rancher.service.hash: 76d82b9309a25e5460531ac297525a19e5a6ee54
lb:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
  metadata:
    io.rancher.service.hash: 71d8a2cfdb029771cf96cc7b5db9316380fd730b
registry:
  scale: 1
  metadata:
    io.rancher.service.hash: c2f7cdf5184286537044b64fbb51f0c0e574e30e
portus:
  scale: 1
  metadata:
    io.rancher.service.hash: 70cf70f82cd8b2af5a2c2b7ec7e4f8ab49cde759
```

Am I doing something wrong?

Thanks for any tips
