### ISSUE TITLE
MongoDB template update is required to version 3.6

### ISSUE THREAD

**Issue by freexmonster** [rancher/community-catalog#709]
I tried to rewrite the config template, but this did not succeed. Need update version to 3.6

**Comment by patrickkeller** [comment]
This is related to the changed default binding behavior in 3.6, see [MongoDB compatibility changes](https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#bind-ip-compatibility). Add to the command in the docker compose file `--bind_ip_all` and it starts working.

**Comment by exocode** [comment]
@freexmonster 
Hi did you fixed the 3.6 update? Can you tell me the status of your progress?

many many thanks in advance

**Comment by exocode** [comment]
My cluster seems to be up with that files:

```yaml
mongo-cluster:
  restart: always
  environment:
    MONGO_SERVICE_NAME: mongo-cluster
    CATTLE_SCRIPT_DEBUG: true
  entrypoint: /opt/rancher/bin/entrypoint.sh
  command:
  - --replSet
  - "rs0"
  image: mongo:3.6
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: mongo-base, mongo-datavolume
  volumes_from:
    - mongo-datavolume
    - mongo-base
mongo-base:
  restart: always
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  image: rancher/mongodb-conf:v0.1.1
  stdin_open: true
  entrypoint: /bin/true
mongo-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /data/db
  entrypoint: /bin/true
  image: busybox

```


```yaml

.catalog:
  name: "MongoDB"
  version: "3.2-rancher1"
  description: "MongoDB Replica Set"
  uuid: mongodb-1
  minimum_rancher_version: v0.46.0
mongo-cluster:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "rs0"

```
